services:
  - type: static
    name: fe
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    redirects:
      - source: "/*"
        destination: "/index.html"
        statusCode: 200
